// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exkndpstzroftbdqotbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4a25kcHN0enJvZnRiZHFvdGJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MDg5NjAsImV4cCI6MjA2OTA4NDk2MH0._49XwVFqu5v9Osw9MMNoqyBPoeJQXabf_eNMpqx6BWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});